module ReportsHelper
  def get_reports_items(reports)
    reports.collect do |report|
      {
        :id => report.id,
        :code_report => report.code_report,
        :contact => report.contact.present? ? { id: report.contact.id, name: report.contact.name } : nil,
        :contact_email => report.contact_email,
        :contact_id => report.contact_id,
        :contact_name => report.contact_name,
        :contact_phone => report.contact_phone,
        :contact_position => report.contact_position,
        :cost_center => {
          id: report.cost_center.id,
          code: report.cost_center.code,
          invoiced_state: report.cost_center.invoiced_state,
          quotation_number: report.cost_center.quotation_number,
          customer: report.cost_center.customer,
          execution_state: report.cost_center.execution_state,
          description: report.cost_center.description,
        },
        :cost_center_id => report.cost_center_id,
        :count => report.count,
        :created_at => report.created_at,
        :customer => report.customer.present? ? { id: report.contact.id, name: report.customer.name } : nil,
        :customer_id => report.customer_id,
        :customer_name => report.customer_name,
        :displacement_hours => report.displacement_hours,
        :last_user_edited => report.last_user_edited.present? ? { id: report.last_user_edited.id, names: report.last_user_edited.names } : nil,
        :last_user_edited_id => report.last_user_edited_id,
        :report_code => report.report_code,
        :report_date => report.report_date,
        :report_execute => report.report_execute.present? ? { id: report.report_execute.id, names: report.report_execute.names } : nil,
        :report_execute_id => report.report_execute_id,
        :report_sate => report.report_sate,
        :total_value => report.total_value,
        :update_user => report.update_user,
        :updated_at => report.updated_at,
        :user => report.user.present? ? { id: report.user.id, names: report.user.names } : nil,
        :user_id => report.user_id,
        :value_displacement_hours => report.value_displacement_hours,
        :viatic_description => report.viatic_description,
        :viatic_value => report.viatic_value,
        :work_description => report.work_description,
        :working_time => report.working_time,
        :working_value => report.working_value,
      }
    end
  end

  def get_report_item(report)
    {
      :id => report.id,
      :code_report => report.code_report,
      :contact => report.contact.present? ? { id: report.contact.id, name: report.contact.name } : nil,
      :contact_email => report.contact_email,
      :contact_id => report.contact_id,
      :contact_name => report.contact_name,
      :contact_phone => report.contact_phone,
      :contact_position => report.contact_position,
      :cost_center => {
        id: report.cost_center.id,
        code: report.cost_center.code,
        invoiced_state: report.cost_center.invoiced_state,
        quotation_number: report.cost_center.quotation_number,
        customer: report.cost_center.customer,
        execution_state: report.cost_center.execution_state,
        description: report.cost_center.description,
      },
      :cost_center_id => report.cost_center_id,
      :count => report.count,
      :created_at => report.created_at,
      :customer => report.customer.present? ? { id: report.contact.id, name: report.customer.name } : nil,
      :customer_id => report.customer_id,
      :customer_name => report.customer_name,
      :displacement_hours => report.displacement_hours,
      :last_user_edited => report.last_user_edited.present? ? { id: report.last_user_edited.id, names: report.last_user_edited.names } : nil,
      :last_user_edited_id => report.last_user_edited_id,
      :report_code => report.report_code,
      :report_date => report.report_date,
      :report_execute => report.report_execute.present? ? { id: report.report_execute.id, names: report.report_execute.names } : nil,
      :report_execute_id => report.report_execute_id,
      :report_sate => report.report_sate,
      :total_value => report.total_value,
      :update_user => report.update_user,
      :updated_at => report.updated_at,
      :user => report.user.present? ? { id: report.user.id, names: report.user.names } : nil,
      :user_id => report.user_id,
      :value_displacement_hours => report.value_displacement_hours,
      :viatic_description => report.viatic_description,
      :viatic_value => report.viatic_value,
      :work_description => report.work_description,
      :working_time => report.working_time,
      :working_value => report.working_value,
    }
  end
end
